name: Build and Deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          mkdir -p build
          CGO_ENABLED=0 GOOS=${{ matrix.os}} GOARCH=${{ matrix.arch }} go build -o build/autommit-build-${{ matrix.os }}-${{ matrix.arch }} ./cmd/autommit/main.go

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/autommit-build-${{ matrix.os }}-${{ matrix.arch }}
          asset_name: autommit-${{ matrix.os }}-${{ matrix.arch }}
          tag: ${{ github.ref }}
