name: Go Test

on: [push, pull_request]

jobs:
  test-go:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.19

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.out
  test-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dive
      run: |
        wget https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
        sudo apt install ./dive_0.9.2_linux_amd64.deb

    - name: Build image
      run: docker build -t autommit:test .

    - name: Test with Dive
      run: dive --ci --ci-config .dive-ci.yaml autommit:test
