name: Go Test

on: [push, pull_request]

jobs:
  test-go:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.out
  test-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build image
      run: docker build -t autommit:test .

    - name: Test with Dive
      uses: yuichielectric/dive-action@0.0.4
      with:
        image: "autommit:test"
        config-file: ${{ github.workspace }}/.dive-ci.yaml
        github-token: ${{ secrets.GITHUB_TOKEN }}

